[package]
name = "dnd-serde-example"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
eyre = "0.6.12"
ron = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.20"
serde_json = "1.0"
serde_yml = "0.0.12"
